"""Curated static data the public APIs don't provide: team brand colors and
circuit technical metadata. Keyed by Ergast/Jolpica refs."""

TEAM_COLORS: dict[str, str] = {
    # current era
    "red_bull": "#3671C6",
    "ferrari": "#E8002D",
    "mercedes": "#27F4D2",
    "mclaren": "#FF8000",
    "aston_martin": "#229971",
    "alpine": "#0093CC",
    "williams": "#64C4FF",
    "rb": "#6692FF",
    "sauber": "#52E252",
    "haas": "#B6BABD",
    "audi": "#00E701",
    "cadillac": "#B8860B",
    # recent history
    "alphatauri": "#5E8FAA",
    "alfa": "#900000",
    "racing_point": "#F596C8",
    "force_india": "#F596C8",
    "renault": "#FFF500",
    "toro_rosso": "#469BFF",
    "lotus_f1": "#FFB800",
    "manor": "#323232",
    "marussia": "#6E0000",
    "caterham": "#048646",
    "hrt": "#B2945B",
    "virgin": "#c82e37",
    "brawn": "#BFD447",
    "toyota": "#CC0000",
    "bmw_sauber": "#0054A6",
    "honda": "#CCCCCC",
    "super_aguri": "#E60012",
    "spyker": "#FF6E14",
    "midland": "#FF0000",
    "jaguar": "#0A5C2F",
    "bar": "#D5D5D5",
    "jordan": "#FFC700",
    "minardi": "#191919",
    "arrows": "#FA9E04",
    "prost": "#03033F",
    "stewart": "#FFFFFF",
    "benetton": "#00A550",
    "tyrrell": "#000066",
    "ligier": "#1E6EB8",
    "brabham": "#00822C",
    "lotus": "#004225",
    "matra": "#0D51C4",
    "cooper": "#004225",
    "vanwall": "#004225",
    "maserati": "#C40000",
    "team_lotus": "#004225",
}

FALLBACK_TEAM_COLOR = "#BFBFBF"

# Curated team logos (hotlinked from Wikimedia) for current-grid teams the
# automatic photos.py pass misses. Applied by seed.py; takes precedence over any
# auto-fetched logo. Ferrari/RB are Wikipedia's non-free logo renders — fine for
# this personal, non-commercial project (user's call, 2026-07-03).
TEAM_LOGOS: dict[str, str] = {
    "mclaren": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/McLaren_Racing_logo.png/330px-McLaren_Racing_logo.png",
    "red_bull": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Red_Bull_Racing_-_2021_Logo.svg/330px-Red_Bull_Racing_-_2021_Logo.svg.png",
    "aston_martin": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Aston_Martin_F1_Team_logo_2024.jpg/330px-Aston_Martin_F1_Team_logo_2024.jpg",
    "cadillac": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cadillac_Formula_1_Team_logo.png/330px-Cadillac_Formula_1_Team_logo.png",
    "ferrari": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Scuderia_Ferrari_HP_logo_24.svg/500px-Scuderia_Ferrari_HP_logo_24.svg.png",
    "rb": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2b/VCARB_F1_logo.svg/500px-VCARB_F1_logo.svg.png",
}

# length_km, corners, drs_zones, track_type, first_gp_year,
# lap_record_time, lap_record_driver, lap_record_year
CIRCUIT_META: dict[str, dict] = {
    "bahrain": dict(length_km=5.412, corners=15, drs_zones=3, track_type="permanent",
                    first_gp_year=2004, lap_record_time="1:31.447",
                    lap_record_driver="Pedro de la Rosa", lap_record_year=2005),
    "jeddah": dict(length_km=6.174, corners=27, drs_zones=3, track_type="street",
                   first_gp_year=2021, lap_record_time="1:30.734",
                   lap_record_driver="Lewis Hamilton", lap_record_year=2021),
    "albert_park": dict(length_km=5.278, corners=14, drs_zones=4, track_type="street",
                        first_gp_year=1996, lap_record_time="1:19.813",
                        lap_record_driver="Charles Leclerc", lap_record_year=2024),
    "suzuka": dict(length_km=5.807, corners=18, drs_zones=1, track_type="permanent",
                   first_gp_year=1987, lap_record_time="1:30.983",
                   lap_record_driver="Lewis Hamilton", lap_record_year=2019),
    "shanghai": dict(length_km=5.451, corners=16, drs_zones=2, track_type="permanent",
                     first_gp_year=2004, lap_record_time="1:32.238",
                     lap_record_driver="Michael Schumacher", lap_record_year=2004),
    "miami": dict(length_km=5.412, corners=19, drs_zones=3, track_type="street",
                  first_gp_year=2022, lap_record_time="1:29.708",
                  lap_record_driver="Max Verstappen", lap_record_year=2023),
    "imola": dict(length_km=4.909, corners=19, drs_zones=1, track_type="permanent",
                  first_gp_year=1980, lap_record_time="1:15.484",
                  lap_record_driver="Lewis Hamilton", lap_record_year=2020),
    "monaco": dict(length_km=3.337, corners=19, drs_zones=1, track_type="street",
                   first_gp_year=1950, lap_record_time="1:12.909",
                   lap_record_driver="Lewis Hamilton", lap_record_year=2021),
    "villeneuve": dict(length_km=4.361, corners=14, drs_zones=3, track_type="street",
                       first_gp_year=1978, lap_record_time="1:13.078",
                       lap_record_driver="Valtteri Bottas", lap_record_year=2019),
    "catalunya": dict(length_km=4.657, corners=14, drs_zones=2, track_type="permanent",
                      first_gp_year=1991, lap_record_time="1:16.330",
                      lap_record_driver="Max Verstappen", lap_record_year=2023),
    "red_bull_ring": dict(length_km=4.318, corners=10, drs_zones=3, track_type="permanent",
                          first_gp_year=1970, lap_record_time="1:05.619",
                          lap_record_driver="Carlos Sainz", lap_record_year=2020),
    "silverstone": dict(length_km=5.891, corners=18, drs_zones=2, track_type="permanent",
                        first_gp_year=1950, lap_record_time="1:27.097",
                        lap_record_driver="Max Verstappen", lap_record_year=2020),
    "hungaroring": dict(length_km=4.381, corners=14, drs_zones=1, track_type="permanent",
                        first_gp_year=1986, lap_record_time="1:16.627",
                        lap_record_driver="Lewis Hamilton", lap_record_year=2020),
    "spa": dict(length_km=7.004, corners=19, drs_zones=2, track_type="permanent",
                first_gp_year=1950, lap_record_time="1:46.286",
                lap_record_driver="Valtteri Bottas", lap_record_year=2018),
    "zandvoort": dict(length_km=4.259, corners=14, drs_zones=2, track_type="permanent",
                      first_gp_year=1952, lap_record_time="1:11.097",
                      lap_record_driver="Lewis Hamilton", lap_record_year=2021),
    "monza": dict(length_km=5.793, corners=11, drs_zones=2, track_type="permanent",
                  first_gp_year=1950, lap_record_time="1:21.046",
                  lap_record_driver="Rubens Barrichello", lap_record_year=2004),
    "baku": dict(length_km=6.003, corners=20, drs_zones=2, track_type="street",
                 first_gp_year=2016, lap_record_time="1:43.009",
                 lap_record_driver="Charles Leclerc", lap_record_year=2019),
    "marina_bay": dict(length_km=4.940, corners=19, drs_zones=3, track_type="street",
                       first_gp_year=2008, lap_record_time="1:34.486",
                       lap_record_driver="Daniel Ricciardo", lap_record_year=2024),
    "americas": dict(length_km=5.513, corners=20, drs_zones=2, track_type="permanent",
                     first_gp_year=2012, lap_record_time="1:36.169",
                     lap_record_driver="Charles Leclerc", lap_record_year=2019),
    "rodriguez": dict(length_km=4.304, corners=17, drs_zones=3, track_type="permanent",
                      first_gp_year=1963, lap_record_time="1:17.774",
                      lap_record_driver="Valtteri Bottas", lap_record_year=2021),
    "interlagos": dict(length_km=4.309, corners=15, drs_zones=2, track_type="permanent",
                       first_gp_year=1973, lap_record_time="1:10.540",
                       lap_record_driver="Valtteri Bottas", lap_record_year=2018),
    "vegas": dict(length_km=6.201, corners=17, drs_zones=2, track_type="street",
                  first_gp_year=2023, lap_record_time="1:34.876",
                  lap_record_driver="Lando Norris", lap_record_year=2024),
    "losail": dict(length_km=5.419, corners=16, drs_zones=1, track_type="permanent",
                   first_gp_year=2021, lap_record_time="1:22.384",
                   lap_record_driver="Lando Norris", lap_record_year=2024),
    "yas_marina": dict(length_km=5.281, corners=16, drs_zones=2, track_type="permanent",
                       first_gp_year=2009, lap_record_time="1:25.637",
                       lap_record_driver="Kevin Magnussen", lap_record_year=2024),
    "madring": dict(length_km=5.474, corners=22, drs_zones=3, track_type="hybrid",
                    first_gp_year=2026),
    # frequent historical circuits
    "nurburgring": dict(length_km=5.148, corners=15, drs_zones=1, track_type="permanent",
                        first_gp_year=1951, lap_record_time="1:29.468",
                        lap_record_driver="Michael Schumacher", lap_record_year=2004),
    "hockenheimring": dict(length_km=4.574, corners=17, drs_zones=2, track_type="permanent",
                           first_gp_year=1970, lap_record_time="1:13.780",
                           lap_record_driver="Kimi Räikkönen", lap_record_year=2004),
    "sepang": dict(length_km=5.543, corners=15, drs_zones=2, track_type="permanent",
                   first_gp_year=1999, lap_record_time="1:34.080",
                   lap_record_driver="Sebastian Vettel", lap_record_year=2017),
    "istanbul": dict(length_km=5.338, corners=14, drs_zones=2, track_type="permanent",
                     first_gp_year=2005, lap_record_time="1:24.770",
                     lap_record_driver="Juan Pablo Montoya", lap_record_year=2005),
    "sochi": dict(length_km=5.848, corners=18, drs_zones=2, track_type="street",
                  first_gp_year=2014, lap_record_time="1:35.761",
                  lap_record_driver="Lewis Hamilton", lap_record_year=2019),
    "portimao": dict(length_km=4.653, corners=15, drs_zones=1, track_type="permanent",
                     first_gp_year=2020, lap_record_time="1:18.750",
                     lap_record_driver="Lewis Hamilton", lap_record_year=2020),
    "mugello": dict(length_km=5.245, corners=15, drs_zones=1, track_type="permanent",
                    first_gp_year=2020, lap_record_time="1:18.833",
                    lap_record_driver="Lewis Hamilton", lap_record_year=2020),
    "ricard": dict(length_km=5.842, corners=15, drs_zones=2, track_type="permanent",
                   first_gp_year=1971, lap_record_time="1:32.740",
                   lap_record_driver="Sebastian Vettel", lap_record_year=2019),
}
